branch-defaults:
    master:
      environment: WorkPals-env
  global:
    application_name: work_pals
    default_ec2_keyname: e-pqimpmyx3q
    default_platform: Node.js
    default_region: us-west-2
    sc: git
